AGENT = 'agent'
SCHEDULER = 'scheduler'
ENV_REQUEST_ID = 'goperation.request_id'

ACTIVE = 1
UNACTIVE = 0
DELETED = -1

MAX_REQUEST_RESULT = 256
MAX_DETAIL_RESULT = 20000
MAX_AGENT_RESULT = 1024
MAX_ENDPOINT_NAME_SIZE = 64
MAX_HOST_NAME_SIZE = 128
MAX_PORT_RANGE_SIZE = 1024
MAX_ROW_PER_REQUEST = 100
ROW_PER_PAGE = MAX_ROW_PER_REQUEST/10