#!/bin/sh
#
# gcenter-wsgi - this script starts and stops the goperation http server daemon
#
# chkconfig:   - 85 15
# description:  goperation http server
# processname:  gcenter-wsgi
# pidfile:     /var/goperation/wsgi.pid

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

CONF_DIR="/etc/goperation/endpoints"

lockfile="/var/lock/subsys/gcenter.wsgi"
prog="gcenter-wsgi"
pyproc="/usr/sbin/"$prog


start() {
    [ -x $nginx ] || exit 5
    [ -f $NGINX_CONF_FILE ] || exit 6
    echo -n $"Starting $prog: "
    daemon $pyproc --config-dir $CONF_DIR
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

prog_status() {
    status $prog
}

q_status() {
    prog_status >/dev/null 2>&1
}


case "$1" in
    start)
        q_status && exit 0
        $1
        ;;
    stop)
        q_status || exit 0
        $1
        ;;
    restart)
        restart
        ;;
    status)
        prog_status
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 2
esac