#!/bin/sh
#
# gop-scheduler - this script starts and stops the goperation scheduler agent daemon
#
# chkconfig:   - 85 15
# description:  goperation scheduler agent
# processname:  gop-scheduler
# pidfile:     /var/goperation/scheduler.pid

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

CONF_DIR="/etc/goperation/endpoints"
STATEPATH="/var/run/goperation"

killtime=35
prog="gop-scheduler"
pyproc="/usr/sbin/"$prog
pidfile=${STATEPATH}/${prog}.pid
lockfile="/var/lock/subsys/"${prog}


start() {
    [ -x $pyproc ] || exit 5
    echo -n $"Starting $prog: "
    daemon $pyproc --config-dir $CONF_DIR --state-path $STATEPATH
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile -d $killtime $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

prog_status() {
    status $prog
}

q_status() {
    prog_status >/dev/null 2>&1
}


case "$1" in
    start)
        q_status && exit 0
        $1
        ;;
    stop)
        q_status || exit 0
        $1
        ;;
    restart)
        restart
        ;;
    status)
        prog_status
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 2
esac