#!/bin/sh
#
# gop-application - this script starts and stops the goperation application agent daemon
#
# chkconfig:   - 85 15
# description:  goperation application agent
# processname:  gop-application
# pidfile:     /var/goperation/application.pid

# Source function library.
. /etc/rc.d/init.d/functions

 Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

CONF_DIR="/etc/goperation/endpoints"

lockfile="/var/lock/subsys/gop.application"
prog="gop-application"
pyproc="/usr/sbin/"$prog


start() {
    [ -x $nginx ] || exit 5
    [ -f $NGINX_CONF_FILE ] || exit 6
    echo -n $"Starting $prog: "
    daemon $pyproc --config-dir $CONF_DIR
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

prog_status() {
    status $prog
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        restart
        ;;
    status)
        prog_status
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 2
esac